server:
  port: 8086
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: validation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redis_combat?useSSL=false&serverTimezone=UTC
    username: root
    password: 1020915

